import type { VehicleConfig } from '../types';

/** 2025 BMW M5 (G90) instrumented-test calibration. */
export const BMW_M5_2025_OVERRIDES: Partial<VehicleConfig> & Record<string, any> = {
  mass: 2381.8135,
  weightDistributionFront: 0.545,
  centerOfGravityHeight: 0.52,
  wheelbase: 3.00482,
  trackWidth: 1.67259,
  wheelRadius: 0.369,
  wheelInertia: 2.10,
  unsprungMassCorner: 55,
  suspensionRestLength: 0.34,
  suspensionStiffness: 62000,
  suspensionDamping: 5000,
  suspensionDampingLowSpeed: 5200,
  suspensionDampingHighSpeed: 3000,
  suspensionReboundDamping: 6500,
  bumpStopStiffness: 70000,
  bumpStopTravelThreshold: 0.80,
  rollStiffnessFront: 46000,
  rollStiffnessRear: 40000,
  antiRollCrossCoupling: 0.30,
  camberStaticFront: -1.5,
  camberStaticRear: -1.2,
  camberGain: 7.5,
  frontCasterDeg: 7.2,
  frontKingpinInclinationDeg: 7.0,
  antiDiveFront: 0.45,
  antiSquatRear: 0.35,
  bodyRollMultiplier: 1.0,
  bodyPitchMultiplier: 1.0,
  tireGripFront: 1.21,
  tireGripRear: 1.20,
  tireStiffness: 15.0,
  tireLoadSensitivity: 0.000030,
  slideFrictionMultiplier: 0.83,
  relaxationLength: 0.50,
  longitudinalRelaxationLength: 0.12,
  longitudinalForceRelaxationLength: 0.066,
  tirePneumaticTrailMax: 0.030,
  tireSidewallStiffness: 230000,
  tireVerticalStiffness: 280000,
  tireVerticalDamping: 1800,
  tireBasePressure: 35.0,
  optimalTireTemp: 75,
  driftAssist: 0.0,
  aeroDownforceFront: 0,
  aeroDownforceRear: 0,
  aeroDragCoeff: 0.35,
  aeroCopPitchSensitivity: 0.04,
  groundEffectUnderbody: false,
  groundEffectMaxDownforce: 0,
  drsEnabled: false,
  airbrakeEnabled: false,
  drivetrain: 'AWD',
  differentialType: 'TORQUE_VECTOR',
  centerFrontTorqueRatio: 0.40,
  diffPowerRamp: 0.88,
  diffCoastRamp: 0.48,
  diffPreloadTorque: 100,
  diffLockRatio: 0.88,
  maxTorque: 700,
  maxRpm: 7200,
  idleRpm: 750,
  revLimiterRpm: 7100,
  flywheelInertia: 0.28,
  engineBrakingTorque: 100,
  clutchBiteRate: 20.0,
  maxClutchTorque: 1500,
  transmissionEfficiency: 0.94,
  turboBoostMaxPsi: 18.0,
  turboSpoolRate: 12.0,
  wastegatePressurePsi: 17.5,
  reverseRatio: -3.97,
  forwardGearRatios: [5.00, 3.20, 2.14, 1.72, 1.30, 1.00, 0.83, 0.64],
  gearRatios: [-3.97, 5.00, 3.20, 2.14, 1.72, 1.30, 1.00, 0.83, 0.64],
  finalDriveRatio: 3.31,
  brakeForce: 10800,
  handbrakeForce: 10000,
  brakeBiasFront: 0.60,

  // BMW-published steering anchors: 14.2:1 overall ratio, 118.3 in wheelbase,
  // 66.3 in front track, speed-sensitive M Servotronic, variable ratio.
  ackermannRatio: 0.90,
  steeringFrontTrackM: 1.68402,
  maxSteerAngle: 0.58,
  steeringRatioCenter: 14.2,
  steeringRatioAtLock: 12.6,

  // Internal rack/EPS values below are engineering calibration, not BMW data.
  steeringRackHalfTravelM: 0.070,
  steeringRackEquivalentInertiaKgm2: 5.8,
  steeringRackDampingNmsPerRad: 46,
  steeringRackFrictionNm: 4.5,
  steeringRackMaxAngularSpeedRadS: 3.2,
  // Keep steady steering authority separate from transient rack response. The first
  // 180 rad/s^2 pass could move the road wheel too far in a single 120 Hz step once
  // column stiffness was raised enough to resist highway SAT. 90 rad/s^2 preserves
  // finite turn-in while leaving equilibrium road-wheel angle unchanged.
  steeringRackMaxAngularAccelRadS2: 90,

  // Effective driver/column stiffness is intentionally much lower than a literal
  // steel steering-column torsion rate because it represents the driver's hands,
  // column/torsion sensor and controller as one input-side compliance. 14 N*m/rad
  // preserves small high-speed steering requests against SAT/mechanical-trail load
  // without bypassing rack inertia, road feedback or the finite rack speed.
  steeringColumnTorsionStiffnessNmPerRad: 14.0,
  steeringColumnTorsionDampingNmsPerRad: 0.18,
  steeringDriverMaxTorqueNm: 8.0,
  steeringEpsParkingGain: 20.0,
  steeringEpsHighSpeedGain: 9.0,
  steeringEpsFadeSpeedMs: 27.8,
  steeringEpsMaxAssistTorqueNm: 65,
  steeringStopStartFraction: 0.92,
  steeringStopStiffnessNmPerRad: 9000,
  steeringStopDampingNmsPerRad: 190,
  steeringTieRodStiffnessNmPerRad: 180000,
  steeringRackMountStiffnessNmPerRad: 250000,
  steeringControlArmBushingStiffnessNmPerRad: 140000,
  steeringTireCarcassStiffnessNmPerRad: 110000,
  steeringComplianceDampingNmsPerRad: 1800,
  steeringMaxComplianceRad: 0.0065,

  steerSpeed: 4.8,
  steerSpeedReduction: 0.60,
  rearSteerMaxDeg: 1.5,
  rearSteerTransitionSpeedMs: 20.0,
  absMode: 'FULL',
  tcsMode: 'SPORT',
  tcsSportSlipThreshold: 0.16,
  tcsSportResponse: 30.0,
  tcsSportGain: 2.6,
  launchControlEnabled: true,
  launchControlRpm: 3000,
  lowSpeedTorqueFillNm: 600,
  torqueFillFadeRpm: 3200,
  automaticTorqueConverter: true,
  shiftDurationSec: 0.07,
  shiftTorqueMultiplier: 0.80,
  drivelineInputInertia: 0.35,
  drivelineInertiaCoupling: 1.0,
};

/** Published Car and Driver acceleration figures; those figures exclude 1-foot rollout. */
export const BMW_M5_2025_TARGETS = {
  zeroTo30MphSec: 1.1,
  zeroTo60MphSec: 3.0,
  zeroTo100MphSec: 6.7,
  quarterMileSec: 10.9,
  quarterMileTrapMph: 130,
  braking70To0Ft: 157,
  braking100To0Ft: 324,
  skidpadG: 0.98,
};

/** Equivalent true-standing-start targets for the simulator's zero-speed stopwatch. */
export const BMW_M5_2025_STANDING_TARGETS = {
  zeroTo30MphSec: 1.3,
  zeroTo60MphSec: 3.2,
  zeroTo100MphSec: 6.9,
  quarterMileSec: 11.1,
  quarterMileTrapMph: 130,
};
